# Generated by Django 4.1 on 2022-10-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_todolist_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='finish',
            field=models.CharField(default='not finished', max_length=225),
        ),
    ]
